import re
import pathlib


def postprocess(tex_path: str) -> None:
    """Remove empty Beamer frames generated by Pandoc edge cases."""
    p = pathlib.Path(tex_path)
    s = p.read_text(encoding="utf-8")
    s = re.sub(r"\\begin\{frame\}\s*\\end\{frame\}\s*", "", s, flags=re.M)
    p.write_text(s, encoding="utf-8")
